name: Flutter CI

# This workflow is triggered on pushes to the repository.
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Setup Java environment
        uses: actions/setup-java@v2
        with:
          java-version: '12.x'
          distribution: 'adopt'
          architecture: 'x64'
          check-latest: false
          server-id: github


      - name: Setup Flutter environment
        uses: subosito/flutter-action@v1
        with:
          channel: "stable"

      - name: Get Flutter dependencies
        run: flutter pub get

      - name: Build APK
        run: flutter build apk --split-per-abi --release

      - name: Push to Releases
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/app/outputs/apk/release/*.apk"
          replacesArtifacts: false
          tag: v0.0.${{ github.run_number }}
          token: ${{ secrets.TOKEN }}
